name: Cloud Browser

on: [workflow_dispatch]

jobs:
  browser:
    runs-on: ubuntu-latest

    steps:

    - name: Start Chrome container
      run: |
        docker run -d -p 3000:3000 browserless/chrome

    - name: Install tunnel
      run: |
        npm install -g localtunnel

    - name: Start tunnel
      run: |
        lt --port 3000
