name: Cloud Laptop

on: [workflow_dispatch]

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:

    - name: Run Desktop Container
      run: |
        docker run -d \
        -p 3000:3000 \
        -e PUID=1000 \
        -e PGID=1000 \
        -e TZ=UTC \
        linuxserver/webtop:ubuntu-xfce

    - name: Install tunnel
      run: |
        npm install -g localtunnel

    - name: Start tunnel
      run: |
       nohup npx localtunnel --port 3000 --subdomain cloudchrome123 > tunnel.log 2>&1 &
        sleep 5
         cat tunnel.log
